# Generated by Django 2.0.5 on 2019-07-20 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imdb_id', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=50)),
                ('directed_by', models.CharField(max_length=50)),
                ('runtime', models.IntegerField()),
                ('notable_casts', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('disc_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('review', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
