# Generated by Django 2.0.5 on 2019-07-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
