# Generated by Django 2.0.5 on 2019-08-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0004_profile'),
        ('mtapp', '0006_auto_20190804_1414'),
    ]

    operations = [
    ]
