# Generated by Django 2.0.5 on 2019-08-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0007_merge_20190805_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
